### ISSUE TITLE
Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.

### ISSUE THREAD

**Issue by ghost** [iwyoo/ConvLSTMCell-tensorflow#3]
Hi,
I got the following error:
Input 'split_dim' of 'Split' Op has type float32 that does not match expected type of int32.
Here is my code: I wish to use convlstm to regress a 14 channel input to a 13 channel output and learn the temporal and spatial information.
    x = tf.placeholder(tf.float32, [None, 46, 46, FLAGS.seq_length, 14]) #input is [batch_size, 46,46,10,14], step size is 10, and it is a 14 channel input. 
    y = tf.placeholder(tf.float32, [None, 46, 46, FLAGS.seq_length, 13])# ground truth data
    lr = tf.placeholder("float")
    _Hsplit = tf.split(x, FLAGS.seq_length, 3)
    _Hsplit = [tf.squeeze(x, [3]) for x in _Hsplit]

    cell = ConvLSTMCell(13)
    state = cell.zero_state(16, 46, 46) #batchsize is 16, height and width is 46.
    x_unwrap = []
    with tf.variable_scope("ConvLSTM") as scope:  # as BasicLSTMCell
        for i, p_input_ in enumerate(_Hsplit):
            if i > 0:
                scope.reuse_variables()
            # ConvCell takes Tensor with size [batch_size, height, width, channel].
            t_output, state = cell(p_input_, state)
            x_unwrap.append(t_output)

    x_unwrap = tf.stack(x_unwrap)
    x_unwrap = tf.transpose(x_unwrap, [1, 0, 2, 3, 4])
    hidden_unwrap = tf.stack(hidden_unwrap)
    hidden_unwrap = tf.transpose(hidden_unwrap, [1, 0, 2, 3, 4])

Thanks for your answer in advance !

**Comment by iwyoo** [comment]
It seems that "FLAGS.seq_length" is float32 type in "_Hsplit = tf.split (x, FLAGS.seq_length, 3)". Please check after change the argument type.
